const currencyList = {
    "ADA": { symbol: "₳", description: "Cardano (crypto)" },
    "AED": { symbol: "د.إ", description: "Dirham Uni Emirat Arab" },
    "AFN": { symbol: "؋", description: "Afghani Afghanistan" },
    "ALL": { symbol: "L", description: "Lek Albania" },
    "AMD": { symbol: "֏", description: "Dram Armenia" },
    "ANG": { symbol: "ƒ", description: "Guilder Antillen Belanda" },
    "AOA": { symbol: "Kz", description: "Kwanza Angola" },
    "ARS": { symbol: "$", description: "Peso Argentina" },
    "ATS": { symbol: "S", description: "Schilling Austria (Mata uang lama)" },
    "AUD": { symbol: "$", description: "Dolar Australia" },
    "AWG": { symbol: "ƒ", description: "Florin Aruba" },
    "AZM": { symbol: "ман", description: "Manat Azerbaijan (Mata uang lama)" },
    "AZN": { symbol: "₼", description: "Manat Azerbaijan" },
    "BAM": { symbol: "KM", description: "Marka Bosnia dan Herzegovina" },
    "BBD": { symbol: "$", description: "Dolar Barbados" },
    "BCH": { symbol: "฿", description: "Bitcoin Cash (crypto)" },
    "BDT": { symbol: "৳", description: "Taka Bangladesh" },
    "BEF": { symbol: "BF", description: "Franco Belgia (Mata uang lama)" },
    "BGN": { symbol: "лв", description: "Lev Bulgaria" },
    "BHD": { symbol: "د.ب", description: "Dinar Bahrain" },
    "BIF": { symbol: "Fr", description: "Franco Burundi (Mata uang lama)" },
    "BMD": { symbol: "$", description: "Dolar Bermuda" },
    "BND": { symbol: "$", description: "Dolar Brunei" },
    "BOB": { symbol: "Bs", description: "Boliviano Bolivia" },
    "BRL": { symbol: "R$", description: "Real Brasil" },
    "BSD": { symbol: "$", description: "Dolar Bahama" },
    "BTC": { symbol: "₿", description: "Bitcoin (crypto)" },
    "BTN": { symbol: "Nu.", description: "Ngultrum Bhutan" },
    "BWP": { symbol: "P", description: "Pula Botswana" },
    "BYN": { symbol: "Br", description: "Rubel Belarus" },
    "BYR": { symbol: "р.", description: "Rubel Belarus (Mata uang lama)" },
    "BZD": { symbol: "$", description: "Dolar Belize" },
    "CAD": { symbol: "$", description: "Dolar Kanada" },
    "CDF": { symbol: "Fr", description: "Franco Kongo" },
    "CHF": { symbol: "CHF", description: "Franc Swiss" },
    "CLF": { symbol: "UF", description: "Unidad de Fomento Chile (Mata uang lama)" },
    "CLP": { symbol: "$", description: "Peso Chili" },
    "CNH": { symbol: "¥", description: "Yuan Tiongkok (Offshore)" },
    "CNY": { symbol: "¥", description: "Yuan Tiongkok" },
    "COP": { symbol: "$", description: "Peso Kolombia" },
    "CRC": { symbol: "₡", description: "Colón Kosta Rika" },
    "CUC": { symbol: "₱", description: "Peso Kuba Konvertibel (Mata uang lama)" },
    "CUP": { symbol: "₱", description: "Peso Kuba" },
    "CVE": { symbol: "Esc", description: "Escudo Kepulauan Verde" },
    "CYP": { symbol: "£", description: "Pound Siprus (Mata uang lama)" },
    "CZK": { symbol: "Kč", description: "Koruna Ceko" },
    "DEM": { symbol: "DM", description: "Marka Jerman (Mata uang lama)" },
    "DJF": { symbol: "Fdj", description: "Franc Djibouti" },
    "DKK": { symbol: "kr", description: "Krone Denmark" },
    "DOGE": { symbol: "Ð", description: "Dogecoin (crypto)" },
    "DOP": { symbol: "RD$", description: "Peso Dominika" },
    "DOT": { symbol: "DOT", description: "Polkadot (crypto)" },
    "DZD": { symbol: "د.ج", description: "Dinar Aljazair" },
    "EEK": { symbol: "kr", description: "Kroon Estonia (Mata uang lama)" },
    "EGP": { symbol: "£", description: "Pound Mesir" },
    "ERN": { symbol: "Nkf", description: "Nakfa Eritrea" },
    "ESP": { symbol: "₧", description: "Peseta Spanyol (Mata uang lama)" },
    "ETB": { symbol: "Br", description: "Birr Etiopia" },
    "ETH": { symbol: "Ξ", description: "Ethereum (crypto)" },
    "EUR": { symbol: "€", description: "Euro" },
    "FIM": { symbol: "mk", description: "Markka Finlandia (Mata uang lama)" },
    "FJD": { symbol: "$", description: "Dolar Fiji" },
    "FKP": { symbol: "£", description: "Pound Kepulauan Falkland" },
    "FRF": { symbol: "₣", description: "Franc Prancis (Mata uang lama)" },
    "GBP": { symbol: "£", description: "Pound Sterling Inggris" },
    "GEL": { symbol: "₾", description: "Lari Georgia" },
    "GGP": { symbol: "£", description: "Pound Guernsey" },
    "GHC": { symbol: "₵", description: "Cedi Ghana (Mata uang lama)" },
    "GHS": { symbol: "₵", description: "Cedi Ghana" },
    "GIP": { symbol: "£", description: "Pound Gibraltar" },
    "GMD": { symbol: "D", description: "Dalasi Gambia" },
    "GNF": { symbol: "Fr", description: "Franco Guinea" },
    "GRD": { symbol: "₯", description: "Drachma Yunani (Mata uang lama)" },
    "GTQ": { symbol: "Q", description: "Quetzal Guatemala" },
    "GYD": { symbol: "$", description: "Dolar Guyana" },
    "HKD": { symbol: "$", description: "Dolar Hong Kong" },
    "HNL": { symbol: "L", description: "Lempira Honduras" },
    "HRK": { symbol: "kn", description: "Kuna Kroasia" },
    "HTG": { symbol: "G", description: "Gourde Haiti" },
    "HUF": { symbol: "Ft", description: "Forint Hungaria" },
    "IDR": { symbol: "Rp", description: "Rupiah Indonesia" },
    "IEP": { symbol: "£", description: "Pound Irlandia (Mata uang lama)" },
    "ILS": { symbol: "₪", description: "Shekel Israel" },
    "IMP": { symbol: "£", description: "Pound Kepulauan Man" },
    "INR": { symbol: "₹", description: "Rupee India" },
    "IQD": { symbol: "ع.د", description: "Dinar Irak" },
    "IRR": { symbol: "﷼", description: "Rial Iran" },
    "ISK": { symbol: "kr", description: "Krona Islandia" },
    "ITL": { symbol: "₯", description: "Lira Italia (Mata uang lama)" },
    "JEP": { symbol: "£", description: "Pound Jersey" },
    "JMD": { symbol: "$", description: "Dolar Jamaika" },
    "JOD": { symbol: "د.أ", description: "Dinar Yordania" },
    "JPY": { symbol: "¥", description: "Yen Jepang" },
    "KES": { symbol: "KSh", description: "Shilling Kenya" },
    "KGS": { symbol: "som", description: "Som Kirgizstan" },
    "KHR": { symbol: "៛", description: "Riel Kamboja" },
    "KMF": { symbol: "Fr", description: "Franco Komoro" },
    "KPW": { symbol: "₩", description: "Won Korea Utara" },
    "KRW": { symbol: "₩", description: "Won Korea Selatan" },
    "KWD": { symbol: "د.ك", description: "Dinar Kuwait" },
    "KYD": { symbol: "$", description: "Dolar Kepulauan Cayman" },
    "KZT": { symbol: "₸", description: "Tenge Kazakhstan" },
    "LAK": { symbol: "₭", description: "Kip Laos" },
    "LBP": { symbol: "ل.ل", description: "Pound Lebanon" },
    "LINK": { symbol: "Ξ", description: "Chainlink (crypto)" },
    "LKR": { symbol: "₨", description: "Rupee Sri Lanka" },
    "LRD": { symbol: "$", description: "Dolar Liberia" },
    "LSL": { symbol: "M", description: "Loti Lesotho" },
    "LTC": { symbol: "Ł", description: "Litecoin (crypto)" },
    "LTL": { symbol: "Lt", description: "Litas Lituania (Mata uang lama)" },
    "LUF": { symbol: "₣", description: "Franc Luksemburg (Mata uang lama)" },
    "LUNA": { symbol: "₺", description: "Luna (crypto)" },
    "LVL": { symbol: "Ls", description: "Lats Latvia (Mata uang lama)" },
    "LYD": { symbol: "د.ل", description: "Dinar Libya" },
    "MAD": { symbol: "د.م.", description: "Dirham Maroko" },
    "MDL": { symbol: "L", description: "Leu Moldova" },
    "MGA": { symbol: "Ar", description: "Ariary Madagaskar" },
    "MGF": { symbol: "Fr", description: "Franc Madagaskar (Mata uang lama)" },
    "MKD": { symbol: "ден", description: "Denar Makedonia Utara" },
    "MMK": { symbol: "K", description: "Kyat Myanmar" },
    "MNT": { symbol: "₮", description: "Tugrik Mongolia" },
    "MOP": { symbol: "MOP", description: "Pataca Makau" },
    "MRO": { symbol: "UM", description: "Ouguiya Mauritania (Mata uang lama)" },
    "MRU": { symbol: "UM", description: "Ouguiya Mauritania" },
    "MTL": { symbol: "Lm", description: "Lira Malta (Mata uang lama)" },
    "MUR": { symbol: "₨", description: "Rupee Mauritius" },
    "MVR": { symbol: "MVR", description: "Rufiyaa Maladewa" },
    "MWK": { symbol: "MK", description: "Kwacha Malawi" },
    "MXN": { symbol: "$", description: "Peso Meksiko" },
    "MXV": { symbol: "UDIS", description: "Unidad de Inversion Meksiko" },
    "MYR": { symbol: "RM", description: "Ringgit Malaysia" },
    "MZM": { symbol: "Mt", description: "Metical Mozambik (Mata uang lama)" },
    "MZN": { symbol: "MT", description: "Metical Mozambik" },
    "NAD": { symbol: "$", description: "Dolar Namibia" },
    "NGN": { symbol: "₦", description: "Naira Nigeria" },
    "NIO": { symbol: "C$", description: "Córdoba Nikaragua" },
    "NLG": { symbol: "fl", description: "Guilder Belanda (Mata uang lama)" },
    "NOK": { symbol: "kr", description: "Krone Norwegia" },
    "NPR": { symbol: "₨", description: "Rupee Nepal" },
    "NZD": { symbol: "$", description: "Dolar Selandia Baru" },
    "OMR": { symbol: "ر.ع.", description: "Rial Oman" },
    "PAB": { symbol: "B/.", description: "Balboa Panama" },
    "PEN": { symbol: "S/.", description: "Sol Peru" },
    "PGK": { symbol: "K", description: "Kina Papua Nugini" },
    "PHP": { symbol: "₱", description: "Peso Filipina" },
    "PKR": { symbol: "₨", description: "Rupee Pakistan" },
    "PLN": { symbol: "zł", description: "Zloty Polandia" },
    "PTE": { symbol: "₧", description: "Peseta Portugal (Mata uang lama)" },
    "PYG": { symbol: "₲", description: "Guarani Paraguay" },
    "QAR": { symbol: "ر.ق", description: "Rial Qatar" },
    "ROL": { symbol: "Lei", description: "Leu Rumania (Mata uang lama)" },
    "RON": { symbol: "lei", description: "Leu Rumania" },
    "RSD": { symbol: "дин", description: "Dinar Serbia" },
    "RUB": { symbol: "₽", description: "Rubel Rusia" },
    "RWF": { symbol: "Fr", description: "Franco Rwanda" },
    "SAR": { symbol: "ر.س", description: "Riyal Arab Saudi" },
    "SBD": { symbol: "$", description: "Dolar Kepulauan Solomon" },
    "SCR": { symbol: "₨", description: "Rupee Seychelles" },
    "SDD": { symbol: "د.ج", description: "Dinar Sudan (Mata uang lama)" },
    "SDG": { symbol: "ج.س", description: "Pound Sudan" },
    "SEK": { symbol: "kr", description: "Krone Swedia" },
    "SGD": { symbol: "$", description: "Dolar Singapura" },
    "SHP": { symbol: "£", description: "Pound Saint Helena" },
    "SIT": { symbol: "T", description: "Tolar Slovenia (Mata uang lama)" },
    "SKK": { symbol: "Sk", description: "Koruna Slovakia (Mata uang lama)" },
    "SLE": { symbol: "Le", description: "Leone Sierra Leone" },
    "SLL": { symbol: "Le", description: "Leone Sierra Leone" },
    "SOS": { symbol: "S", description: "Shilling Somalia" },
    "SPL": { symbol: "SP", description: "Special Drawing Rights (SDR)" },
    "SRD": { symbol: "$", description: "Dolar Suriname" },
    "SRG": { symbol: "SRG", description: "Guilder Suriname (Mata uang lama)" },
    "STD": { symbol: "Db", description: "Dobra São Tomé dan Príncipe" },
    "STN": { symbol: "Db", description: "Dobra São Tomé dan Príncipe" },
    "SVC": { symbol: "$", description: "Colón El Salvador" },
    "SYP": { symbol: "£", description: "Pound Suriah" },
    "SZL": { symbol: "L", description: "Lilangeni Swaziland" },
    "THB": { symbol: "฿", description: "Baht Thailand" },
    "TJS": { symbol: "ЅМ", description: "Somoni Tajikistan" },
    "TMM": { symbol: "m", description: "Manat Turkmenistan (Mata uang lama)" },
    "TMT": { symbol: "m", description: "Manat Turkmenistan" },
    "TND": { symbol: "د.ت", description: "Dinar Tunisia" },
    "TOP": { symbol: "T$", description: "Paʻanga Tonga" },
    "TRL": { symbol: "₤", description: "Lira Turki (Mata uang lama)" },
    "TRY": { symbol: "₺", description: "Lira Turki" },
    "TTD": { symbol: "$", description: "Dolar Trinidad dan Tobago" },
    "TVD": { symbol: "$", description: "Dolar Tuvalu" },
    "TWD": { symbol: "$", description: "Dolar Taiwan" },
    "TZS": { symbol: "Sh", description: "Shilling Tanzania" },
    "UAH": { symbol: "₴", description: "Hryvnia Ukraina" },
    "UGX": { symbol: "USh", description: "Shilling Uganda" },
    "UNI": { symbol: "Ξ", description: "Uniswap (crypto)" },
    "USD": { symbol: "$", description: "Dolar Amerika Serikat" },
    "UYU": { symbol: "$", description: "Peso Uruguay" },
    "UZS": { symbol: "лв", description: "Sum Uzbekistan" },
    "VAL": { symbol: "V$" , description: "Valora (crypto)" },
    "VEB": { symbol: "Bs.", description: "Bolívar Venezuela (Mata uang lama)" },
    "VED": { symbol: "₡", description: "Venezuelan Bolívar (crypto)" },
    "VEF": { symbol: "Bs.F", description: "Bolívar Venezuela (Mata uang lama)" },
    "VES": { symbol: "Bs.S", description: "Bolívar Venezuela" },
    "VND": { symbol: "₫", description: "Dong Vietnam" },
    "VUV": { symbol: "Vt", description: "Vatu Vanuatu" },
    "WST": { symbol: "T", description: "Tala Samoa" },
    "XAF": { symbol: "Fr", description: "Franco Afrika Tengah" },
    "XAG": { symbol: "XAG", description: "Perak (logam)" },
    "XAU": { symbol: "XAU", description: "Emas (logam)" },
    "XBT": { symbol: "XBT", description: "Bitcoin (crypto)" },
    "XCD": { symbol: "EC$", description: "Dolar Karibia Timur" },
    "XDR": { symbol: "XDR", description: "Hak Penarikan Khusus (SDR)" },
    "XLM": { symbol: "XLM", description: "Stellar (crypto)" },
    "XOF": { symbol: "Fr", description: "Franco Afrika Barat" },
    "XPD": { symbol: "XPD", description: "Paladium (logam)" },
    "XPF": { symbol: "Fr", description: "Franco Pasifik Prancis" },
    "XPT": { symbol: "XPT", description: "Platinum (logam)" },
    "XRP": { symbol: "XRP", description: "Ripple (crypto)" },
    "YER": { symbol: "ر.ي", description: "Rial Yaman" },
    "ZAR": { symbol: "R", description: "Rand Afrika Selatan" },
    "ZMK": { symbol: "ZK", description: "Kwacha Zambia (Mata uang lama)" },
    "ZMW": { symbol: "K", description: "Kwacha Zambia" },
    "ZWD": { symbol: "Z$" , description: "Dolar Zimbabwe (Mata uang lama)" },
    "ZWG": { symbol: "ZW$", description: "Guilder Zimbabwe (Mata uang lama)" },
    "ZWL": { symbol: "ZWL$", description: "Dolar Zimbabwe" }
};
function getCurrencyList() {
  const result = [`List Mata Uang:\n\n${global.readmore}`];
  for (const [code, details] of Object.entries(currencyList)) {
    const { symbol, description } = details;
    result.push(`${code} = ${description || "Tidak ada deskripsi"}`);
  }
  return result.join("\n");
}
function isCurrencyValid(from) {
    return currencyList.hasOwnProperty(from);
}

module.exports = { currencyList,
                  getCurrencyList,
                  isCurrencyValid
                 };
  


