const languageListIntl = {
  "aa": "Afar",
  "ab": "Abkhazian",
  "ae": "Avestan",
  "af": "Afrikaans",
  "ak": "Akan",
  "am": "Amharic",
  "an": "Aragonese",
  "ao": "Albanian",
  "ar": "Arabic",
  "as": "Assamese",
  "av": "Avaric",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "ba": "Bashkir",
  "be": "Belarusian",
  "bg": "Bulgarian",
  "bh": "Bihari languages",
  "bi": "Bislama",
  "bm": "Bambara",
  "bn": "Bengali",
  "bo": "Tibetan",
  "br": "Breton",
  "bs": "Bosnian",
  "ca": "Catalan",
  "ce": "Chechen",
  "ch": "Chamorro",
  "co": "Corsican",
  "cr": "Cree",
  "cs": "Czech",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "da": "Danish",
  "de": "German",
  "dv": "Divehi",
  "dz": "Dzongkha",
  "ee": "Ewe",
  "el": "Greek",
  "en": "English",
  "eo": "Esperanto",
  "es": "Spanish",
  "et": "Estonian",
  "eu": "Basque",
  "fa": "Persian",
  "ff": "Fula",
  "fi": "Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fr": "French",
  "fy": "Frisian",
  "ga": "Irish",
  "gd": "Scots Gaelic",
  "gl": "Galician",
  "gn": "Guarani",
  "gu": "Gujarati",
  "gv": "Manx",
  "ha": "Hausa",
  "he": "Hebrew",
  "hi": "Hindi",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "ht": "Haitian Creole",
  "hu": "Hungarian",
  "hy": "Armenian",
  "hz": "Herero",
  "ia": "Interlingua",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ii": "Sichuan Yi",
  "ik": "Inupiat",
  "io": "Ido",
  "is": "Icelandic",
  "it": "Italian",
  "iu": "Inuktitut",
  "ja": "Japanese",
  "ka": "Georgian",
  "kk": "Kazakh",
  "kl": "Kalaallisut",
  "km": "Khmer",
  "kn": "Kannada",
  "ko": "Korean",
  "kr": "Kanuri",
  "ks": "Kashmiri",
  "ku": "Kurdish",
  "kv": "Komi",
  "kw": "Cornish",
  "ky": "Kirghiz",
  "la": "Latin",
  "lb": "Luxembourgish",
  "lo": "Lao",
  "lt": "Lithuanian",
  "lu": "Luba-Katanga",
  "lv": "Latvian",
  "mg": "Malagasy",
  "mh": "Marshallese",
  "mk": "Macedonian",
  "ml": "Malayalam",
  "mn": "Mongolian",
  "mr": "Marathi",
  "ms": "Malay",
  "mt": "Maltese",
  "my": "Burmese",
  "na": "Nauru",
  "nb": "Norwegian Bokmål",
  "nd": "North Ndebele",
  "ne": "Nepali",
  "ng": "Ndonga",
  "nl": "Dutch",
  "nn": "Norwegian Nynorsk",
  "no": "Norwegian",
  "nr": "South Ndebele",
  "nv": "Navajo",
  "ny": "Nyanja",
  "oc": "Occitan",
  "oj": "Ojibwe",
  "om": "Oromo",
  "or": "Oriya",
  "os": "Ossetian",
  "pa": "Punjabi",
  "pl": "Polish",
  "ps": "Pashto",
  "pt": "Portuguese",
  "qu": "Quechua",
  "rm": "Romansh",
  "rn": "Kirundi",
  "ro": "Romanian",
  "ru": "Russian",
  "rw": "Kinyarwanda",
  "sa": "Sanskrit",
  "sc": "Sardinian",
  "sd": "Sindhi",
  "se": "Northern Sami",
  "sg": "Sango",
  "si": "Sinhalese",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sm": "Samoan",
  "sn": "Shona",
  "so": "Somali",
  "sq": "Albanian",
  "sr": "Serbian",
  "ss": "Swati",
  "st": "Sotho",
  "sv": "Swedish",
  "sw": "Swahili",
  "ta": "Tamil",
  "te": "Telugu",
  "tg": "Tajik",
  "th": "Thai",
  "ti": "Tigrinya",
  "tk": "Turkmen",
  "tl": "Tagalog",
  "tn": "Tswana",
  "to": "Tongan",
  "tr": "Turkish",
  "ts": "Tsonga",
  "tt": "Tatar",
  "tw": "Twi",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "uz": "Uzbek",
  "ve": "Venda",
  "vi": "Vietnamese",
  "vo": "Volapük",
  "wa": "Walloon",
  "wo": "Wolof",
  "xh": "Xhosa",
  "yi": "Yiddish",
  "zu": "Zulu",
  "als": "Alsace",
  "ja-romaji": "Japanese Romaji",
  "ja-kana": "Japanese Katakana",
  "ja-hira": "Japanese hiragana"
/*"en-US": "English (United States)",
  "en-GB": "English (United Kingdom)",
  "en-AU": "English (Australia)",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canada)",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "pt-PT": "Portuguese (Portugal)",
  "pt-BR": "Portuguese (Brazil)",
  "zh-CN": "Chinese (Simplified, China)",
  "zh-TW": "Chinese (Traditional, Taiwan)",
  "zh-HK": "Chinese (Traditional, Hong Kong)",
  "ja-JP": "Japanese (Japan)",
  "ko-KR": "Korean (South Korea)",
  "de-DE": "German (Germany)",
  "de-CH": "German (Switzerland)",
  "it-IT": "Italian (Italy)",
  "ru-RU": "Russian (Russia)",
  "ar-SA": "Arabic (Saudi Arabia)",
  "ar-EG": "Arabic (Egypt)",
  "hi-IN": "Hindi (India)",
  "bn-IN": "Bengali (India)",
  "ta-IN": "Tamil (India)",
  "ml-IN": "Malayalam (India)",
  "te-IN": "Telugu (India)",
  "vi-VN": "Vietnamese (Vietnam)",
  "ms-MY": "Malay (Malaysia)",
  "th-TH": "Thai (Thailand)",
  "tr-TR": "Turkish (Turkey)",
  "pl-PL": "Polish (Poland)",
  "cs-CZ": "Czech (Czech Republic)",
  "nl-NL": "Dutch (Netherlands)",
  "sv-SE": "Swedish (Sweden)",
  "da-DK": "Danish (Denmark)",
  "fi-FI": "Finnish (Finland)",
  "no-NO": "Norwegian (Norway)",
  "sk-SK": "Slovak (Slovakia)",
  "el-GR": "Greek (Greece)",
  "hu-HU": "Hungarian (Hungary)",
  "ro-RO": "Romanian (Romania)",
  "sr-RS": "Serbian (Serbia)",
  "hr-HR": "Croatian (Croatia)",
  "pl-PL": "Polish (Poland)",
  "sw-KE": "Swahili (Kenya)",
  "zu-ZA": "Zulu (South Africa)",
  "sq-AL": "Albanian (Albania)",
  "sq-XK": "Albanian (Kosovo)",
  "bs-BA": "Bosnian (Bosnia and Herzegovina)",
  "mk-MK": "Macedonian (North Macedonia)",
  "cy-GB": "Welsh (United Kingdom)",
  "gl-ES": "Galician (Spain)",
  "eu-ES": "Basque (Spain)",
  "ca-ES": "Catalan (Spain)",
  "km-KH": "Khmer (Cambodia)",
  "ml-IN": "Malayalam (India)",
  "mr-IN": "Marathi (India)",
  "si-LK": "Sinhalese (Sri Lanka)",
  "ne-NP": "Nepali (Nepal)",
  "my-MM": "Burmese (Myanmar)",
  "sn-ZW": "Shona (Zimbabwe)"*/
}; //Add more international language as needed

const languageListDom = {
    'id': 'Indonesian Language',
    'id-ID': 'Indonesian Language',
    'ace': 'Aceh',
    'ban': 'Bali',
    'jv': 'Jawa',
    'su': 'Sunda',
    'btx': 'Batak Toba',
    'bts': 'Batak Simalungun',
    'bbc': 'Batak Karo',
    'bew': 'Bewel',
    'mad': 'Madura',
    'mak': 'Makassar',
    'min': 'Minangkabau',
    'tet': 'Tetun'
}; //Add more Indonesian language as needed
module.exports = {
    languageListIntl,
    languageListDom
    };
