-- CreateTable
CREATE TABLE `users` (
    `jid` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL DEFAULT '',
    `pushName` VARCHAR(191) NOT NULL DEFAULT '',
    `gender` VARCHAR(191) NOT NULL DEFAULT 'lk',
    `registered` BOOLEAN NOT NULL DEFAULT false,
    `age` BIGINT NOT NULL DEFAULT -1,
    `regTime` BIGINT NOT NULL DEFAULT -1,
    `regSince` BIGINT NOT NULL DEFAULT 0,
    `setName` BIGINT NOT NULL DEFAULT 0,
    `setAge` BIGINT NOT NULL DEFAULT 0,
    `sn` VARCHAR(191) NOT NULL DEFAULT '',
    `banned` BOOLEAN NOT NULL DEFAULT false,
    `bannedTime` BIGINT NOT NULL DEFAULT 0,
    `Banneduser` BOOLEAN NOT NULL DEFAULT false,
    `bannedReason` VARCHAR(191) NOT NULL DEFAULT '',
    `banLevel` BIGINT NOT NULL DEFAULT 0,
    `lastBanTime` BIGINT NOT NULL DEFAULT 0,
    `warn` BIGINT NOT NULL DEFAULT 0,
    `moderator` BOOLEAN NOT NULL DEFAULT false,
    `timSupport` BOOLEAN NOT NULL DEFAULT false,
    `bannedUntil` BIGINT NOT NULL DEFAULT 0,
    `afk` BIGINT NOT NULL DEFAULT -1,
    `afkReason` VARCHAR(191) NOT NULL DEFAULT '',
    `premium` BIGINT NOT NULL DEFAULT 0,
    `premiumTime` BIGINT NOT NULL DEFAULT 0,
    `exifPack` VARCHAR(191) NOT NULL DEFAULT '',
    `exifAuthor` VARCHAR(191) NOT NULL DEFAULT '',
    `exp` BIGINT NOT NULL DEFAULT 0,
    `level` BIGINT NOT NULL DEFAULT 0,
    `coin` BIGINT NOT NULL DEFAULT 0,
    `atm` BIGINT NOT NULL DEFAULT 0,
    `limit` BIGINT NOT NULL DEFAULT 500,
    `glimit` BIGINT NOT NULL DEFAULT 10,
    `tprem` BIGINT NOT NULL DEFAULT 0,
    `tigame` BIGINT NOT NULL DEFAULT 5,
    `lbars` VARCHAR(191) NOT NULL DEFAULT '[▒▒▒▒▒▒▒▒▒]',
    `role` VARCHAR(191) NOT NULL DEFAULT 'Newbie ㋡',
    `autolevelup` BOOLEAN NOT NULL DEFAULT false,
    `job` VARCHAR(191) NOT NULL DEFAULT 'Pengangguran',
    `jobexp` BIGINT NOT NULL DEFAULT 0,
    `vip` VARCHAR(191) NOT NULL DEFAULT 'tidak',
    `vipPoin` BIGINT NOT NULL DEFAULT 0,
    `ajd` BIGINT NOT NULL DEFAULT 0,
    `skata` BIGINT NOT NULL DEFAULT 0,
    `jail` BOOLEAN NOT NULL DEFAULT false,
    `penjara` BOOLEAN NOT NULL DEFAULT false,
    `dirawat` BOOLEAN NOT NULL DEFAULT false,
    `kingdom` BOOLEAN NOT NULL DEFAULT false,
    `statusNikah` BOOLEAN NOT NULL DEFAULT false,
    `tanggalNikah` BIGINT NOT NULL DEFAULT 0,
    `hamil` BOOLEAN NOT NULL DEFAULT false,
    `hamilStart` BIGINT NOT NULL DEFAULT 0,
    `lastKencan` BIGINT NOT NULL DEFAULT 0,
    `lastCekAyang` BIGINT NOT NULL DEFAULT 0,
    `lastRawatAnak` BIGINT NOT NULL DEFAULT 0,
    `slotNetWinLoss` DOUBLE NOT NULL DEFAULT 0,
    `_spinLock` BOOLEAN NOT NULL DEFAULT false,
    `slotFreeSpins` BIGINT NOT NULL DEFAULT 0,
    `slotFSBet` DOUBLE NOT NULL DEFAULT 0,
    `freespin` BIGINT NOT NULL DEFAULT 0,
    `fsBet` DOUBLE NOT NULL DEFAULT 0,
    `slotSpinning` BOOLEAN NOT NULL DEFAULT false,
    `isAutoSpinning` BOOLEAN NOT NULL DEFAULT false,
    `cancelAutoSpin` BOOLEAN NOT NULL DEFAULT false,
    `lastslot` BIGINT NOT NULL DEFAULT 0,
    `ds` JSON NOT NULL,
    `chatgpt` JSON NOT NULL,
    `guildId` VARCHAR(191) NULL,
    `gift` JSON NOT NULL,
    `portofolio` JSON NOT NULL,
    `invest` JSON NOT NULL,
    `anak` JSON NOT NULL,
    `properti` JSON NULL,
    `pasanganChar` JSON NULL,
    `lastCharSearch` JSON NULL,
    `perkerjaandua` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`jid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_economy` (
    `jid` VARCHAR(191) NOT NULL,
    `saldo` DOUBLE NOT NULL DEFAULT 0,
    `pengeluaran` DOUBLE NOT NULL DEFAULT 0,
    `money` DOUBLE NOT NULL DEFAULT 0,
    `bank` DOUBLE NOT NULL DEFAULT 0,
    `balance` DOUBLE NOT NULL DEFAULT 0,
    `chip` BIGINT NOT NULL DEFAULT 0,
    `tiketcoin` BIGINT NOT NULL DEFAULT 0,
    `poin` BIGINT NOT NULL DEFAULT 0,
    `litecoin` BIGINT NOT NULL DEFAULT 0,
    `gems` BIGINT NOT NULL DEFAULT 0,
    `cupon` BIGINT NOT NULL DEFAULT 0,
    `dana` BIGINT NOT NULL DEFAULT 0,
    `gopay` BIGINT NOT NULL DEFAULT 0,
    `ovo` BIGINT NOT NULL DEFAULT 0,
    `diamond` BIGINT NOT NULL DEFAULT 0,
    `emerald` BIGINT NOT NULL DEFAULT 0,
    `berlian` BIGINT NOT NULL DEFAULT 0,
    `iron` BIGINT NOT NULL DEFAULT 0,
    `emas` BIGINT NOT NULL DEFAULT 0,
    `arlok` BIGINT NOT NULL DEFAULT 0,
    `bisnis` BIGINT NOT NULL DEFAULT 0,
    `berbisnis` BIGINT NOT NULL DEFAULT 0,
    `rumahsakit` BIGINT NOT NULL DEFAULT 0,
    `fortress` BIGINT NOT NULL DEFAULT 0,
    `shield` BOOLEAN NOT NULL DEFAULT false,
    `pertanian` BIGINT NOT NULL DEFAULT 0,
    `pertambangan` BIGINT NOT NULL DEFAULT 0,
    `camptroops` BIGINT NOT NULL DEFAULT 0,
    `tambang` BIGINT NOT NULL DEFAULT 0,
    `penduduk` BIGINT NOT NULL DEFAULT 0,
    `archer` BIGINT NOT NULL DEFAULT 0,
    `subscribers` BIGINT NOT NULL DEFAULT 0,
    `viewers` BIGINT NOT NULL DEFAULT 0,
    `like` BIGINT NOT NULL DEFAULT 0,
    `playButton` BIGINT NOT NULL DEFAULT 0,
    `taxi` BIGINT NOT NULL DEFAULT 0,
    `common` BIGINT NOT NULL DEFAULT 0,
    `as` BIGINT NOT NULL DEFAULT 0,
    `uncommon` BIGINT NOT NULL DEFAULT 0,
    `mythic` BIGINT NOT NULL DEFAULT 0,
    `legendary` BIGINT NOT NULL DEFAULT 0,
    `glory` BIGINT NOT NULL DEFAULT 0,
    `enchant` BIGINT NOT NULL DEFAULT 0,
    `pet` BIGINT NOT NULL DEFAULT 0,
    `psepick` BIGINT NOT NULL DEFAULT 0,
    `psenjata` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`jid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_rpg` (
    `jid` VARCHAR(191) NOT NULL,
    `healt` BIGINT NOT NULL DEFAULT 100,
    `health` BIGINT NOT NULL DEFAULT 100,
    `energi` BIGINT NOT NULL DEFAULT 100,
    `power` BIGINT NOT NULL DEFAULT 100,
    `stamina` BIGINT NOT NULL DEFAULT 100,
    `haus` BIGINT NOT NULL DEFAULT 100,
    `laper` BIGINT NOT NULL DEFAULT 100,
    `title` BIGINT NOT NULL DEFAULT 0,
    `titlein` VARCHAR(191) NOT NULL DEFAULT 'Belum Ada',
    `ultah` VARCHAR(191) NOT NULL DEFAULT '',
    `pasangan` VARCHAR(191) NOT NULL DEFAULT '',
    `sahabat` VARCHAR(191) NOT NULL DEFAULT '',
    `location` VARCHAR(191) NOT NULL DEFAULT 'Gubuk',
    `husbu` VARCHAR(191) NOT NULL DEFAULT 'Belum Di Set',
    `waifu` VARCHAR(191) NOT NULL DEFAULT 'Belum Di Set',
    `follow` BIGINT NOT NULL DEFAULT 0,
    `lastfollow` BIGINT NOT NULL DEFAULT 0,
    `followers` BIGINT NOT NULL DEFAULT 0,
    `pc` BIGINT NOT NULL DEFAULT 0,
    `korbanngocok` BIGINT NOT NULL DEFAULT 0,
    `ngewe` BIGINT NOT NULL DEFAULT 0,
    `jualan` BIGINT NOT NULL DEFAULT 0,
    `ngocokk` BIGINT NOT NULL DEFAULT 0,
    `antarpaket` BIGINT NOT NULL DEFAULT 0,
    `ojekk` BIGINT NOT NULL DEFAULT 0,
    `polisi` BIGINT NOT NULL DEFAULT 0,
    `ojek` BIGINT NOT NULL DEFAULT 0,
    `pedagang` BIGINT NOT NULL DEFAULT 0,
    `dokter` BIGINT NOT NULL DEFAULT 0,
    `petani` BIGINT NOT NULL DEFAULT 0,
    `montir` BIGINT NOT NULL DEFAULT 0,
    `kuli` BIGINT NOT NULL DEFAULT 0,
    `trofi` BIGINT NOT NULL DEFAULT 0,
    `rtrofi` VARCHAR(191) NOT NULL DEFAULT 'Perunggu',
    `troopcamp` BIGINT NOT NULL DEFAULT 0,
    `attack` BIGINT NOT NULL DEFAULT 0,
    `strenght` BIGINT NOT NULL DEFAULT 0,
    `speed` BIGINT NOT NULL DEFAULT 0,
    `defense` BIGINT NOT NULL DEFAULT 0,
    `regeneration` BIGINT NOT NULL DEFAULT 0,
    `skill` VARCHAR(191) NOT NULL DEFAULT '',
    `korps` VARCHAR(191) NOT NULL DEFAULT '',
    `korpsgrade` VARCHAR(191) NOT NULL DEFAULT '',
    `breaths` VARCHAR(191) NOT NULL DEFAULT '',
    `magic` VARCHAR(191) NOT NULL DEFAULT '',
    `demon` VARCHAR(191) NOT NULL DEFAULT '',
    `darahiblis` BIGINT NOT NULL DEFAULT 0,
    `demonblood` BIGINT NOT NULL DEFAULT 0,
    `demonkill` BIGINT NOT NULL DEFAULT 0,
    `hashirakill` BIGINT NOT NULL DEFAULT 0,
    `alldemonkill` BIGINT NOT NULL DEFAULT 0,
    `allhashirakill` BIGINT NOT NULL DEFAULT 0,
    `ramuan` BIGINT NOT NULL DEFAULT 0,
    `string` BIGINT NOT NULL DEFAULT 0,
    `eleksirb` BIGINT NOT NULL DEFAULT 0,
    `shadow` BIGINT NOT NULL DEFAULT 0,
    `antispam` BIGINT NOT NULL DEFAULT 0,
    `antispamlastclaim` BIGINT NOT NULL DEFAULT 0,
    `healthmonster` BIGINT NOT NULL DEFAULT 0,
    `pancing` BIGINT NOT NULL DEFAULT 0,
    `pancingan` BIGINT NOT NULL DEFAULT 0,
    `totalPancingan` BIGINT NOT NULL DEFAULT 0,
    `anakpancingan` BIGINT NOT NULL DEFAULT 0,
    `umpan` BIGINT NOT NULL DEFAULT 0,
    `sampah` BIGINT NOT NULL DEFAULT 0,
    `potion` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`jid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_cooldown` (
    `jid` VARCHAR(191) NOT NULL,
    `lastseen` BIGINT NOT NULL DEFAULT 0,
    `lastSetStatus` BIGINT NOT NULL DEFAULT 0,
    `lastIstigfar` BIGINT NOT NULL DEFAULT 0,
    `lastclaim` BIGINT NOT NULL DEFAULT 0,
    `judilast` BIGINT NOT NULL DEFAULT 0,
    `lastnambang` BIGINT NOT NULL DEFAULT 0,
    `lastnebang` BIGINT NOT NULL DEFAULT 0,
    `lastkerja` BIGINT NOT NULL DEFAULT 0,
    `lastmaling` BIGINT NOT NULL DEFAULT 0,
    `lastbunuhi` BIGINT NOT NULL DEFAULT 0,
    `lastbisnis` BIGINT NOT NULL DEFAULT 0,
    `lastberbisnis` BIGINT NOT NULL DEFAULT 0,
    `lastmancing` BIGINT NOT NULL DEFAULT 0,
    `lastramuanclaim` BIGINT NOT NULL DEFAULT 0,
    `lastgemclaim` BIGINT NOT NULL DEFAULT 0,
    `lastpotionclaim` BIGINT NOT NULL DEFAULT 0,
    `laststringclaim` BIGINT NOT NULL DEFAULT 0,
    `lastswordclaim` BIGINT NOT NULL DEFAULT 0,
    `lastweaponclaim` BIGINT NOT NULL DEFAULT 0,
    `lastironclaim` BIGINT NOT NULL DEFAULT 0,
    `lastmancingclaim` BIGINT NOT NULL DEFAULT 0,
    `lastadventure` BIGINT NOT NULL DEFAULT 0,
    `lastberburu` BIGINT NOT NULL DEFAULT 0,
    `lastkill` BIGINT NOT NULL DEFAULT 0,
    `lastfishing` BIGINT NOT NULL DEFAULT 0,
    `lastdungeon` BIGINT NOT NULL DEFAULT 0,
    `lastwar` BIGINT NOT NULL DEFAULT 0,
    `lastsda` BIGINT NOT NULL DEFAULT 0,
    `lastberbru` BIGINT NOT NULL DEFAULT 0,
    `lastduel` BIGINT NOT NULL DEFAULT 0,
    `lastjb` BIGINT NOT NULL DEFAULT 0,
    `lastmining` BIGINT NOT NULL DEFAULT 0,
    `lasthunt` BIGINT NOT NULL DEFAULT 0,
    `lasthun` BIGINT NOT NULL DEFAULT 0,
    `lastngocok` BIGINT NOT NULL DEFAULT 0,
    `lastgift` BIGINT NOT NULL DEFAULT 0,
    `lastrob` BIGINT NOT NULL DEFAULT 0,
    `lastngojek` BIGINT NOT NULL DEFAULT 0,
    `lastngewe` BIGINT NOT NULL DEFAULT 0,
    `lastjualan` BIGINT NOT NULL DEFAULT 0,
    `lastngocokk` BIGINT NOT NULL DEFAULT 0,
    `lastgrab` BIGINT NOT NULL DEFAULT 0,
    `lastberkebon` BIGINT NOT NULL DEFAULT 0,
    `lastcodereg` BIGINT NOT NULL DEFAULT 0,
    `lastdagang` BIGINT NOT NULL DEFAULT 0,
    `lasthourly` BIGINT NOT NULL DEFAULT 0,
    `lastweekly` BIGINT NOT NULL DEFAULT 0,
    `lastyearly` BIGINT NOT NULL DEFAULT 0,
    `lastmonthly` BIGINT NOT NULL DEFAULT 0,
    `lastturu` BIGINT NOT NULL DEFAULT 0,
    `lastbansos` BIGINT NOT NULL DEFAULT 0,
    `lastrampok` BIGINT NOT NULL DEFAULT 0,
    `lastngaji` BIGINT NOT NULL DEFAULT 0,
    `lastlonte` BIGINT NOT NULL DEFAULT 0,
    `lastkoboy` BIGINT NOT NULL DEFAULT 0,
    `lastdate` BIGINT NOT NULL DEFAULT 0,
    `lasttambang` BIGINT NOT NULL DEFAULT 0,
    `lastngepet` BIGINT NOT NULL DEFAULT 0,
    `lasttaxi` BIGINT NOT NULL DEFAULT 0,
    `lastyoutuber` BIGINT NOT NULL DEFAULT 0,
    `lastbossbattle` BIGINT NOT NULL DEFAULT 0,
    `lastberbisnis2` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`jid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_job` (
    `jid` VARCHAR(191) NOT NULL,
    `kerjasatu` BIGINT NOT NULL DEFAULT 0,
    `kerjadua` BIGINT NOT NULL DEFAULT 0,
    `kerjatiga` BIGINT NOT NULL DEFAULT 0,
    `kerjaempat` BIGINT NOT NULL DEFAULT 0,
    `kerjalima` BIGINT NOT NULL DEFAULT 0,
    `kerjaenam` BIGINT NOT NULL DEFAULT 0,
    `kerjatujuh` BIGINT NOT NULL DEFAULT 0,
    `kerjadelapan` BIGINT NOT NULL DEFAULT 0,
    `kerjasembilan` BIGINT NOT NULL DEFAULT 0,
    `kerjasepuluh` BIGINT NOT NULL DEFAULT 0,
    `kerjasebelas` BIGINT NOT NULL DEFAULT 0,
    `kerjaduabelas` BIGINT NOT NULL DEFAULT 0,
    `kerjatigabelas` BIGINT NOT NULL DEFAULT 0,
    `kerjaempatbelas` BIGINT NOT NULL DEFAULT 0,
    `kerjalimabelas` BIGINT NOT NULL DEFAULT 0,
    `pekerjaansatu` BIGINT NOT NULL DEFAULT 0,
    `pekerjaandua` BIGINT NOT NULL DEFAULT 0,
    `pekerjaantiga` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanempat` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanlima` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanenam` BIGINT NOT NULL DEFAULT 0,
    `pekerjaantujuh` BIGINT NOT NULL DEFAULT 0,
    `pekerjaandelapan` BIGINT NOT NULL DEFAULT 0,
    `pekerjaansembilan` BIGINT NOT NULL DEFAULT 0,
    `pekerjaansepuluh` BIGINT NOT NULL DEFAULT 0,
    `pekerjaansebelas` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanduabelas` BIGINT NOT NULL DEFAULT 0,
    `pekerjaantigabelas` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanempatbelas` BIGINT NOT NULL DEFAULT 0,
    `pekerjaanlimabelas` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`jid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_inventory` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `jid` VARCHAR(191) NOT NULL,
    `itemName` VARCHAR(191) NOT NULL,
    `itemCategory` VARCHAR(191) NOT NULL DEFAULT 'resource',
    `quantity` BIGINT NOT NULL DEFAULT 0,

    UNIQUE INDEX `user_inventory_jid_itemName_key`(`jid`, `itemName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_tools` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `jid` VARCHAR(191) NOT NULL,
    `toolName` VARCHAR(191) NOT NULL,
    `owned` BIGINT NOT NULL DEFAULT 0,
    `durability` BIGINT NOT NULL DEFAULT 0,

    UNIQUE INDEX `user_tools_jid_toolName_key`(`jid`, `toolName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_pets` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `jid` VARCHAR(191) NOT NULL,
    `petName` VARCHAR(191) NOT NULL,
    `count` BIGINT NOT NULL DEFAULT 0,
    `baby` BIGINT NOT NULL DEFAULT 0,
    `exp` BIGINT NOT NULL DEFAULT 0,
    `food` BIGINT NOT NULL DEFAULT 0,
    `lastClaim` BIGINT NOT NULL DEFAULT 0,

    UNIQUE INDEX `user_pets_jid_petName_key`(`jid`, `petName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `chats` (
    `chatId` VARCHAR(191) NOT NULL,
    `onlyAdmin` BOOLEAN NOT NULL DEFAULT false,
    `isBanned` BOOLEAN NOT NULL DEFAULT false,
    `welcome` BOOLEAN NOT NULL DEFAULT true,
    `welcometype` BIGINT NOT NULL DEFAULT 1,
    `detect` BOOLEAN NOT NULL DEFAULT false,
    `isBannedTime` BOOLEAN NOT NULL DEFAULT false,
    `mute` BOOLEAN NOT NULL DEFAULT false,
    `listStr` LONGTEXT NOT NULL DEFAULT '{}',
    `sWelcome` TEXT NOT NULL DEFAULT 'Hai, @user!
Selamat datang di grup @subject

@desc',
    `sBye` TEXT NOT NULL DEFAULT 'Selamat tinggal @user!',
    `sPromote` TEXT NOT NULL DEFAULT '',
    `sDemote` TEXT NOT NULL DEFAULT '',
    `delete` BOOLEAN NOT NULL DEFAULT true,
    `antiLink` BOOLEAN NOT NULL DEFAULT true,
    `antiLinknokick` BOOLEAN NOT NULL DEFAULT false,
    `antiSticker` BOOLEAN NOT NULL DEFAULT false,
    `antiStickernokick` BOOLEAN NOT NULL DEFAULT false,
    `viewonce` BOOLEAN NOT NULL DEFAULT false,
    `antiToxic` BOOLEAN NOT NULL DEFAULT false,
    `antiDelete` BOOLEAN NOT NULL DEFAULT false,
    `antibot` BOOLEAN NOT NULL DEFAULT false,
    `expired` BIGINT NOT NULL DEFAULT 0,
    `memgc` LONGTEXT NOT NULL DEFAULT '{}',
    `blacklistUsers` LONGTEXT NOT NULL DEFAULT '{}',
    `rpg` BOOLEAN NOT NULL DEFAULT false,
    `antilinkig` BOOLEAN NOT NULL DEFAULT false,
    `antilinkignokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinkfb` BOOLEAN NOT NULL DEFAULT false,
    `antilinkfbnokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinktwit` BOOLEAN NOT NULL DEFAULT false,
    `antilinktwitnokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinkyt` BOOLEAN NOT NULL DEFAULT false,
    `antilinkytnokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinktele` BOOLEAN NOT NULL DEFAULT false,
    `antilinktelenokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinkwame` BOOLEAN NOT NULL DEFAULT false,
    `antilinkwamenokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinkall` BOOLEAN NOT NULL DEFAULT false,
    `antilinkallnokick` BOOLEAN NOT NULL DEFAULT false,
    `antilinktt` BOOLEAN NOT NULL DEFAULT false,
    `antilinkttnokick` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`chatId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `guilds` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `isPrivate` BOOLEAN NOT NULL DEFAULT false,
    `owner` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `level` INTEGER NOT NULL DEFAULT 1,
    `exp` INTEGER NOT NULL DEFAULT 0,
    `eliksir` INTEGER NOT NULL DEFAULT 0,
    `harta` BIGINT NOT NULL DEFAULT 0,
    `guardian` VARCHAR(191) NULL,
    `attack` INTEGER NOT NULL DEFAULT 0,
    `staff` JSON NOT NULL,
    `waitingRoom` JSON NOT NULL,
    `members` JSON NOT NULL,

    UNIQUE INDEX `guilds_owner_key`(`owner`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `command_stats` (
    `pluginName` VARCHAR(191) NOT NULL,
    `total` BIGINT NOT NULL DEFAULT 0,
    `success` BIGINT NOT NULL DEFAULT 0,
    `last` BIGINT NOT NULL DEFAULT 0,
    `lastSuccess` BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (`pluginName`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `user_economy` ADD CONSTRAINT `user_economy_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_rpg` ADD CONSTRAINT `user_rpg_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_cooldown` ADD CONSTRAINT `user_cooldown_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_job` ADD CONSTRAINT `user_job_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_inventory` ADD CONSTRAINT `user_inventory_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_tools` ADD CONSTRAINT `user_tools_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_pets` ADD CONSTRAINT `user_pets_jid_fkey` FOREIGN KEY (`jid`) REFERENCES `users`(`jid`) ON DELETE CASCADE ON UPDATE CASCADE;
